version: "2"
run:
  modules-download-mode: readonly
output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
linters:
  enable:
    - gocritic
    - misspell
    - unconvert
    - unparam
    - whitespace
  settings:
    gocritic:
      disabled-checks:
        - hugeParam
      enabled-tags:
        - diagnostic
        - style
        - performance
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - unparam
        path: _test\.go
      - linters:
          - govet
        text: 'shadow: declaration of "err"'
      # Ignore Close() and Rollback() method calls - common practice to ignore these in defer
      - linters:
          - errcheck
        text: 'Close` is not checked'
      - linters:
          - errcheck
        text: 'Rollback` is not checked'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/yatisql/yatisql-go
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
